{% set name = "elabapy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7bcb2f3822db6fb9c7b8a80b93c0cc82c139e82c8abe338e1474ded9b20bba8b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - elabapy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/elabftw/elabapy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENCE
  summary: elabftw API to manage experiments and items
  description: |
    This library provides easy access to eLabFTW's API.
  doc_url: https://doc.elabftw.net/api.html
  dev_url: https://github.com/elabftw/elabapy

extra:
  recipe-maintainers:
    - din14970
